//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaPatitas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public int IdTipo { get; set; }
        public string Raza { get; set; }
        public int Edad { get; set; }
        public int IdTamanio { get; set; }
        public string Sexo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Tamanio Tamanio { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
